"""Initial migration

Revision ID: 8be710088486
Revises:
Create Date: 2025-12-05 22:58:05.418435

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8be710088486"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("code", sa.VARCHAR(length=3), nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("sign", sa.VARCHAR(length=10), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencies_code"), "currencies", ["code"], unique=True)
    op.create_table(
        "exchange_rates",
        sa.Column("base_currency_id", sa.Integer(), nullable=False),
        sa.Column("target_currency_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.DECIMAL(precision=21, scale=6), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["base_currency_id"], ["currencies.id"]),
        sa.ForeignKeyConstraint(["target_currency_id"], ["currencies.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_base_id_target_id_unique", "exchange_rates", ["base_currency_id", "target_currency_id"], unique=True
    )
    op.create_index(op.f("ix_exchange_rates_base_currency_id"), "exchange_rates", ["base_currency_id"], unique=False)
    op.create_index(
        op.f("ix_exchange_rates_target_currency_id"), "exchange_rates", ["target_currency_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_target_currency_id"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_base_currency_id"), table_name="exchange_rates")
    op.drop_index("ix_base_id_target_id_unique", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index(op.f("ix_currencies_code"), table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
